config/routes.rb
Rails.application.routes.draw do
  root   'menus#index'
  get    '/show/:id',         to: 'menus#show', as: 'show'
  get    '/confirm',          to: 'menus#confirm'
  get    '/history',          to: 'menus#history'
  get    '/check',            to: 'menus#check'
  get    '/thanks',           to: 'menus#thanks'
  post   '/call',             to: 'menus#call'
  get    '/new',              to: 'menus#new'
  post   '/menus',            to: 'menus#create'
  delete '/menus',            to: 'menus#destroy'
  patch  '/menus/:id',        to: 'menus#update', as: 'menu'
  get    '/:id/edit',         to: 'menus#edit', as: 'edit'
  post   '/:id/edit',         to: 'menus#sold_out', as: 'sold_out'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  get    '/logout',           to: 'sessions#delete'
  delete '/logout',           to: 'sessions#destroy'
  post   '/',                 to: 'carts#add_item'
  post   '/confirm',          to: 'carts#update_item'
  delete '/delete_item',      to: 'carts#delete_item'
  get    'orders/show',       to: 'orders#show', as: 'order'
  patch  'history_items/:id', to: 'orders#checked', as: 'checked'
  resources :users
  resources :carts, only: [:show, :destroy]
  resources :tables, only: [:show, :create, :new]
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  has_one_attached :image
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
                      size:         { less_than: 5.megabytes,
                                      message: "should be less than 5MB" }
  has_many :cart_items, dependent: :destroy 
  has_many :history_items, dependent: :destroy
  # 表示用のリサイズ済み画像を返す
  def display_image
    image.variant(resize_to_limit: [105, 105])
  end
  attribute :existence, :boolean, default: true
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :logged_in_user, only: [:new, :edit, :create, :destroy]

  def index
    @cart_items = current_cart.cart_items
    @menus = Menu.all
  end

  def show
    @menu = Menu.find_by(id: params[:id])
  end

  def confirm
    @cart_items = current_cart.cart_items
    @cart = current_cart
  end

  def history
    @history_items = current_history.history_items
  end

  def check
    @history_items = current_history.history_items
  end

  def thanks
    history = current_history
    history.destroy
      if current_cart
        cart = current_cart
        cart.destroy
      end
    session.delete(:cart_id)
    session.delete(:history_id)
    session.delete(:table_id)
  end

  def new
    @menu = Menu.new 
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.image.attach(params[:menu][:image])
      if @menu.save
        flash[:success] = "メニューが追加されました"
        redirect_to root_url
      else
        flash.now[:danger] = "不具合が発生しました"
        render 'menus/new'
      end
  end

  def edit
    @menu = Menu.find_by(id: params[:id])
    if !@menu
      flash[:danger] = "メニューが存在しません"
      redirect_to root_url
    end
  end
  
  def update
    @menu = Menu.find_by(id: params[:id])
    if @menu.update(menu_params)
      flash[:success] = "メニュー内容が更新されました"
      redirect_to root_url
    else
      flash.now[:danger] = "不具合が発生しました"
      render 'edit'
    end
  end

  def destroy
    menu = Menu.find_by(id: params[:id])
    if menu
      menu.destroy
      flash[:success] = "メニューが削除されました"
      redirect_to root_url
    else 
      flash[:danger] = "メニューが存在しません"
      redirect_to root_url
    end
  end

  def sold_out
    menu = Menu.find_by(id: params[:id])
    if menu
      menu.toggle(:existence)
      menu.save
      redirect_to root_url
    else
      flash[:danger] = "メニューが存在しません"
      redirect_to root_url
    end
  end

  def call
    ActionCable.server.broadcast 'order_channel', order: render_order(params[:table_id])
    flash[:success] = "スタッフをお呼びしています。少々お待ちください。"
    redirect_to root_url
  end

  private

    def render_order(table_id)
      ApplicationController.renderer.render(partial: 'orders/call', locals: { table: table_id })
    end

    def menu_params
      params.require(:menu).permit(:content, :name, :price, :image, :category)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/check.html.erb
<div class="header">
  <h1 class="header_title">注文リスト<h1>
</div>
<div class="sub_header">
  <%= link_to(root_path, class: "sub_header_link") do %>
  <i class="fas fa-angle-left icon"></i>
  メニュー選択に戻る
  <% end %>
</div>
<div class="total">

  <%= render 'layouts/total_list', items: @history_items %>

  <div class="round_btn round_btn_red">
    <%= link_to "確定", thanks_path %>
  </div>
</div>

<div class="main">
  <div class="orderlist_content">
    <ul class="orderlist_contents_items_list">

      <%= render @history_items %>

    </ul>
  </div>
</div>

app/views/menus/confirm.html.erb
<div class="header">
  <h1 class="header_title">注文リスト<h1>
</div>
<div class="sub_header">
  <%= link_to(root_path, class: "sub_header_link") do %>
  <i class="fas fa-angle-left icon"></i>
  メニュー選択に戻る
  <% end %>
</div>
<div class="total">
  <div class="render">
    <%= render 'layouts/total_list', items: @cart_items %>
  </div>
  <div class="round_btn round_btn_red">
    <%= link_to "注文をする", cart_path(@cart), method: :delete, class: "order_confirmation", data: { "disable-with": "保存しています..." } %>
  </div>
</div>

<div class="main">
  <div class="orderlist_content">
    <ul class="orderlist_contents_items_list">
      <% @cart_items.each do |item| %>
      <div id=<%= item.menu.name %>>
        <%= render 'cart_items/cart_item', cart_item: item %>
      </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/menus/edit.html.erb
<% provide(:button_text, '変更') %>
<%= render 'layouts/form' %>

app/views/menus/history.html.erb
<div class="header">
  <div class="header_title">注文リスト</div>
  <div class="header_btn header_btn_red">
    <%= link_to "お会計", check_path, class: "header_btn_inner" %>
  </div>
</div>
<div class="sub_header">
  <%= link_to(root_path, class: "sub_header_link") do %>
  <i class="fas fa-angle-left icon"></i>
  メニュー選択に戻る
  <% end %>
</div>
<div class="total">

  <%= render 'layouts/total_list', items: @history_items %>

</div>

<div class="main">
  <div class="orderlist_content">
    <ul class="orderlist_contents_items_list">

      <%= render @history_items %>

    </ul>
  </div>
</div>

app/views/menus/index.html.erb
<main>
	<div class="justify-content-center">
		<div class="wrapper menu">

			<div class="header">
				<h1 class="header_title">
					<% if logged_in? %>
					<%= link_to "QR Order", user_path(current_user)%>
					<% else %>
					QR Order
					<% end %>
				</h1>

				<div class="btn_wrapper">
					<% if session[:table_id] %>
					<div class="header_btn header_btn_blue">
						<%= link_to "呼出", call_path(table_id: session[:table_id]), class: "header_btn_inner",  method: :post %>
					</div>
					<% end %>
					<div class="header_btn header_btn_blue">
						<%= link_to "履歴", history_path, class: "header_btn_inner" %>
					</div>
					<div class="header_btn header_btn_red">
						<%= link_to "お会計", check_path, class: "header_btn_inner" %>
					</div>
				</div>

			</div>

			<div class="main">
				<div class="menu_sidenavi">
					<ul class="menu_sidenavi_list">
						<% @menus.pluck(:category).uniq.each do |category| %>
						<li class="menu_sidenavi_listitem">
							<%= link_to category, root_path(category: category) %>
						</li>
						<% end %>
					</ul>
				</div>
				<div class="menu_content">
					<div class="menu_content_items">
						<% if params[:category] %>
						<h2 class="menu_content_items_title">
							<%= params[:category] %>
						</h2>
						<ul class="menu_content_items_list">
							<% @menus.where(category: params[:category]).find_each do |menu| %>
							<div id=<%= menu.name %>>
								<%= render 'layouts/menu', menu: menu, cart_items: @cart_items %>
							</div>
							<% end %>
						</ul>
						<% else %>
						<% @menus.pluck(:category).uniq.each do |category| %>
						<h2 class="menu_content_items_title">
							<%= category %>
						</h2>
						<ul class="menu_content_items_list">
							<% @menus.where(category: category).find_each do |menu| %>
							<div id=<%= menu.name %>>
								<%= render 'layouts/menu', menu: menu, cart_items: @cart_items %>
							</div>
							<% end %>
						</ul>
						<% end %>
						<% end %>
					</div>
				</div>
			</div>
			<div class="menu_total">

				<%= render 'layouts/total', cart_items: @cart_items %>

				<div class="menu_order_btn">
					<%= link_to "ご注文", confirm_path %>
				</div>
			</div>
		</div>
	</div>
</main>

app/views/menus/menu.html.erb
<main class="py-4">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12">
  			<div class="wrapper menu">                    
					<div class="header">
						<div class="header_setting">
							<%= link_to "その他", "#", class: "header_btn_inner" %>
						</div>
						<h1 class="header_title">
							Cafe QR Order
						</h1>
						<div class="header_btn header_btn_blue">
							<%= link_to "履歴", "#", class: "header_btn_inner" %>
						</div>
						<div class="header_btn header_btn_red">
							<%= link_to "お会計", "#", class: "header_btn_inner" %>
						</div>
					</div>

					<div class="main">
						<div class="menu_sidenavi">
							<ul class="menu_sidenavi_list">
								<li class="menu_sidenavi_listitem"></li>
							</ul>
						</div>
						<div class="menu_content">
							<div class="menu_content_items">
								<h2 class="menu_content_items_title"></h2>
								<ul class="menu_content_items_list">
									<li class="menu_content_items_listitem"></li>
								</ul>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</main>

app/views/menus/new.html.erb
<% provide(:button_text, '作成') %>
<%= render 'layouts/form' %>

app/views/menus/show.html.erb
<div class="header">
  <h1 class="header_title">メニュー詳細<h1>
</div>
<div class="sub_header">
  <%= link_to(root_path, class: "sub_header_link") do %>
  <i class="fas fa-angle-left icon"></i>
  メニュー選択に戻る
  <% end %>
</div>
<div class="item_detail">
  <div class="item_detail_container">
    <div class="item_detail_img">
      <%= image_tag @menu.display_image if @menu.image.attached? %>
    </div>
    <div class="item_detail_info">
      <p class="item_detail_name">
        <%= @menu.name %>
      </p>
      <p class="item_detail_price">
        <%= @menu.price %><span class="text_gray">(税込)</span>
      </p>
      <p class="item_detail_description">
        <%= @menu.content %>
      </p>
      <% if logged_in? %>
      <ul>
        <li><%= link_to "メニュー編集", edit_path(id: @menu.id) %></li>
        <li>
          <%= link_to "メニュー削除", menus_path(id: @menu.id), method: :delete,
                                                              data: { confirm: "削除しますか？" } %>
        </li>
        <% if @menu.existence %>
        <li><%= link_to "売り切れ", sold_out_path(id: @menu.id), method: :post %></li>
        <% else %>
        <li><%= link_to "売り切れ状態解除", sold_out_path(id: @menu.id), method: :post %></li>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/menus/thanks.html.erb
<div class="wrapper">

  <div class="header">
    <h1 class="header_title">
      ご利用ありがとうございました
    </h1>
  </div>

  <div class="main">
    <div class="complete_content">
      <div class="complete_text">
        <span class="complete_text_description">
          レジにてお会計をお願いいたします
        </span>
      </div>
    </div>
  </div>

</div>