config/routes.rb
Rails.application.routes.draw do
  root   'menus#index'
  get    '/show/:id',         to: 'menus#show', as: 'show'
  get    '/confirm',          to: 'menus#confirm'
  get    '/history',          to: 'menus#history'
  get    '/check',            to: 'menus#check'
  get    '/thanks',           to: 'menus#thanks'
  post   '/call',             to: 'menus#call'
  get    '/new',              to: 'menus#new'
  post   '/menus',            to: 'menus#create'
  delete '/menus',            to: 'menus#destroy'
  patch  '/menus/:id',        to: 'menus#update', as: 'menu'
  get    '/:id/edit',         to: 'menus#edit', as: 'edit'
  post   '/:id/edit',         to: 'menus#sold_out', as: 'sold_out'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  get    '/logout',           to: 'sessions#delete'
  delete '/logout',           to: 'sessions#destroy'
  post   '/',                 to: 'carts#add_item'
  post   '/confirm',          to: 'carts#update_item'
  delete '/delete_item',      to: 'carts#delete_item'
  get    'orders/show',       to: 'orders#show', as: 'order'
  patch  'history_items/:id', to: 'orders#checked', as: 'checked'
  resources :users
  resources :carts, only: [:show, :destroy]
  resources :tables, only: [:show, :create, :new]
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: true
  has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "QR Orderへようこそ！"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def show
    @history_items = HistoryItem.all
    @tables = Table.all
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="col-md-6 offset-md-3">
  <section class="form">
    <h1>アカウント登録</h1>
    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name, "名前" %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email, "Eメール" %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "パスワード確認用" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "アカウント作成", class: "btn btn-primary" %>
    <% end %>
  </section>
</div>

app/views/users/show.html.erb
<div class="header">
  <h1 class="header_title">
    QR Order
  </h1>
</div>
<div class="order_list col-md-6 offset-md-3">
  <ul class="list-group">
    <li class="list-group-item"><%= link_to "メニュー一覧", root_path %></li>
    <li class="list-group-item"><%= link_to "注文履歴", order_path %></li>
    <li class="list-group-item"><%= link_to "メニュー作成", new_path %></li>
    <li class="list-group-item"><%= link_to "テーブル作成", new_table_path %></li>
    <li class="list-group-item"><%= link_to "ログアウト", logout_path %></li>
    <li class="list-group-item">
      現在のテーブル<br>
      <% @tables.each do |table| %>
      <%= table.table_number %>番
      <% end %>
    </li>
  </ul>
</div>