config/routes.rb
Rails.application.routes.draw do
  root   'menus#index'
  get    '/show/:id',         to: 'menus#show', as: 'show'
  get    '/confirm',          to: 'menus#confirm'
  get    '/history',          to: 'menus#history'
  get    '/check',            to: 'menus#check'
  get    '/thanks',           to: 'menus#thanks'
  post   '/call',             to: 'menus#call'
  get    '/new',              to: 'menus#new'
  post   '/menus',            to: 'menus#create'
  delete '/menus',            to: 'menus#destroy'
  patch  '/menus/:id',        to: 'menus#update', as: 'menu'
  get    '/:id/edit',         to: 'menus#edit', as: 'edit'
  post   '/:id/edit',         to: 'menus#sold_out', as: 'sold_out'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  get    '/logout',           to: 'sessions#delete'
  delete '/logout',           to: 'sessions#destroy'
  post   '/',                 to: 'carts#add_item'
  post   '/confirm',          to: 'carts#update_item'
  delete '/delete_item',      to: 'carts#delete_item'
  get    'orders/show',       to: 'orders#show', as: 'order'
  patch  'history_items/:id', to: 'orders#checked', as: 'checked'
  resources :users
  resources :carts, only: [:show, :destroy]
  resources :tables, only: [:show, :create, :new]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @history_items = HistoryItem.all.order(created_at: :desc)
  end

  def checked
    order = HistoryItem.find_by(id: params[:id])
    order.toggle(:checked)
    order.save
    redirect_to order_path
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/orders/_call.html.erb
<li class="list-group-item">
  <%= table %>番テーブルから呼出です
</li>

app/views/orders/_order.html.erb
<% if order.quantity != 0 %>
<li class="list-group-item" id=<%= "item#{order.id}" %>>
  <div>
    <% if order.checked %>
    <i class="far fa-check-square"></i>
    <% else %>
    <i class="far fa-square"></i>
    <% end %>
    <%= order.menu.name %>
    テーブル<%= order.tables_id %>から
    <%= order.quantity %>個の注文
  </div>

  <% if order.checked %>
  <%= button_to "未対応に戻す", checked_path(id: order.id), class: "order_btn", method: :patch %>
  <% else %>
  <%= button_to "対応完了", checked_path(id: order.id), class: "order_btn", method: :patch %>
  <% end %>
</li>
<% end %>

app/views/orders/show.html.erb
<div class="header">
  <h1 class="header_title">
    注文履歴
  </h1>
</div>
<div class="sub_header">
  <%= link_to user_path(current_user), class: "sub_header_link" do %>
  <i class="fas fa-angle-left icon"></i>
  従業員メニューへ
  <% end %>
</div>
<div class="order_list col-md-6 offset-md-3">
  <ul class="list-group" id='orders'>
    <% @history_items.each do |order| %>
    <div id=<%= "container#{order.id}" %>>
      <div id=<%= order.id %>>
        <%= render partial: 'orders/order', locals: {order: order} %>
      </div>
    </div>
    <% end %>
  </ul>
</div>