config/routes.rb
Rails.application.routes.draw do
  root   'menus#index'
  get    '/show/:id',         to: 'menus#show', as: 'show'
  get    '/confirm',          to: 'menus#confirm'
  get    '/history',          to: 'menus#history'
  get    '/check',            to: 'menus#check'
  get    '/thanks',           to: 'menus#thanks'
  post   '/call',             to: 'menus#call'
  get    '/new',              to: 'menus#new'
  post   '/menus',            to: 'menus#create'
  delete '/menus',            to: 'menus#destroy'
  patch  '/menus/:id',        to: 'menus#update', as: 'menu'
  get    '/:id/edit',         to: 'menus#edit', as: 'edit'
  post   '/:id/edit',         to: 'menus#sold_out', as: 'sold_out'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  get    '/logout',           to: 'sessions#delete'
  delete '/logout',           to: 'sessions#destroy'
  post   '/',                 to: 'carts#add_item'
  post   '/confirm',          to: 'carts#update_item'
  delete '/delete_item',      to: 'carts#delete_item'
  get    'orders/show',       to: 'orders#show', as: 'order'
  patch  'history_items/:id', to: 'orders#checked', as: 'checked'
  resources :users
  resources :carts, only: [:show, :destroy]
  resources :tables, only: [:show, :create, :new]
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :menu
  belongs_to :cart
  attribute :quantity, :integer, default: 0
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_cart_item.html.erb
<% if cart_item.quantity != 0 %>
<% menu = Menu.find_by(id: cart_item.menu_id) %>
<li class="orderlist_contents_items_listitem">
  <%= image_tag menu.display_image, class: "orderlist_item_img" if menu.image.attached? %>
  <div class="menu_item_info">
    <p class="menu_item_info_name">
      <%= menu.name %>
    </p>
    <p class="menu_item_info_price">
      <%= menu.price %>円<span class="text-gray">(税込)</span>
    </p>
    <div class="item_number_btn">
      <% if cart_item.quantity == 1 %>
      <div class="item_number_minus">
        <i class="fas fa-minus icon disabled"></i>
      </div>
      <% else %>
      <div class="item_number_minus">
        <%= button_to confirm_path, {remote: true, params: {id: "minus", quantity: cart_item.quantity, menu_id: menu.id }} do %>
        <i class="fas fa-minus icon"></i>
        <% end %>
      </div>
      <% end %>
      <div class="number_box">
        <span class="item_number">
          <%= cart_item.quantity %>
        </span>
      </div>
      <div class="item_number_plus">
        <%= button_to confirm_path, {remote: true, params: {id: "plus", quantity: cart_item.quantity, menu_id: menu.id }} do %>
        <i class="fas fa-plus icon"></i>
        <% end %>
      </div>
    </div>
    <%= link_to "削除", delete_item_path(menu_id: cart_item.menu_id), method: :delete, class: "orderlist_items_option_delete",
                                                              data: { confirm: "削除しますか？" } %>
  </div>
</li>
<% end %>